### Pandas
- Dataframe - Special Object to data in tabular form(rows & columns)



### Installation

In [2]:
!pip install pandas

You are using pip version 18.0, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
import numpy as np
import pandas as pd

In [8]:
# Try to create a data frame
user_data = {
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(1,100,5),
}

In [9]:
user_data

{'MarksA': array([82, 25, 62, 18,  5]),
 'MarksB': array([76, 94, 76, 97, 65]),
 'MarksC': array([93, 85,  7, 65, 94])}

In [15]:
df = pd.DataFrame(user_data,dtype='float32')
print(df)

   MarksA  MarksB  MarksC
0    82.0    76.0    93.0
1    25.0    94.0    85.0
2    62.0    76.0     7.0
3    18.0    97.0    65.0
4     5.0    65.0    94.0


In [16]:
df.head(n=3)

MarksA  MarksB  MarksC
0    82.0    76.0    93.0
1    25.0    94.0    85.0
2    62.0    76.0     7.0

In [17]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [18]:
df.to_csv('marks.csv')

In [25]:
my_data = pd.read_csv('marks.csv')
my_data = my_data.drop(columns=['Unnamed: 0'])
my_data

MarksA  MarksB  MarksC
0    82.0    76.0    93.0
1    25.0    94.0    85.0
2    62.0    76.0     7.0
3    18.0    97.0    65.0
4     5.0    65.0    94.0

## Pandas Basics-2

In [26]:
my_data.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   38.400000  81.600000  68.800000
std    32.284671  13.501852  36.458195
min     5.000000  65.000000   7.000000
25%    18.000000  76.000000  65.000000
50%    25.000000  76.000000  85.000000
75%    62.000000  94.000000  93.000000
max    82.000000  97.000000  94.000000

In [28]:
my_data.tail(n=3)

MarksA  MarksB  MarksC
2    62.0    76.0     7.0
3    18.0    97.0    65.0
4     5.0    65.0    94.0

In [29]:
# Row
df.iloc[3]

MarksA    18.0
MarksB    97.0
MarksC    65.0
Name: 3, dtype: float32

In [30]:
# Row & Col
df.iloc[3,1]

97.0

In [31]:
df.iloc[3][1]

97.0

In [35]:
idx = [df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(idx)
df.iloc[3,idx]

[1, 2]


MarksB    97.0
MarksC    65.0
Name: 3, dtype: float32

In [36]:
df.iloc[:3,idx]

MarksB  MarksC
0    76.0    93.0
1    94.0    85.0
2    76.0     7.0

In [37]:
df.iloc[:3,[1,2]]

MarksB  MarksC
0    76.0    93.0
1    94.0    85.0
2    76.0     7.0

In [38]:
## Sort your dataframe

In [39]:
my_data

MarksA  MarksB  MarksC
0    82.0    76.0    93.0
1    25.0    94.0    85.0
2    62.0    76.0     7.0
3    18.0    97.0    65.0
4     5.0    65.0    94.0

In [42]:
my_data.sort_values(by=["MarksC","MarksA"],ascending=False)

MarksA  MarksB  MarksC
4     5.0    65.0    94.0
0    82.0    76.0    93.0
1    25.0    94.0    85.0
3    18.0    97.0    65.0
2    62.0    76.0     7.0

In [43]:
data_array = my_data.values

In [45]:
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [46]:
print(data_array)

[[82. 76. 93.]
 [25. 94. 85.]
 [62. 76.  7.]
 [18. 97. 65.]
 [ 5. 65. 94.]]


In [47]:
print(type(data_array))

<class 'numpy.ndarray'>


In [48]:
data_array.shape

(5, 3)

In [50]:
data_array[2][2]

7.0

In [51]:
# Numpy arraays back into dataframe

In [53]:
new_df = pd.DataFrame(data_array,dtype='int32',columns=["Physics","Chem","Maths"])

In [54]:
new_df

Physics  Chem  Maths
0       82    76     93
1       25    94     85
2       62    76      7
3       18    97     65
4        5    65     94

In [57]:
new_df.to_csv("PCM.csv",index=False)

In [58]:
pcm = pd.read_csv('PCM.csv')

In [59]:
print(pcm)

   Physics  Chem  Maths
0       82    76     93
1       25    94     85
2       62    76      7
3       18    97     65
4        5    65     94
