### Working with Numpy - for mathematical operations

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [14]:
# Create Zeros, Ones, Custom array
a = np.zeros((3,3))
print(a)

b = np.ones((2,3))
print(b)

#Array of some constants
c = np.full((3,2),5)
print(c)

#Identity Matrix - Size/Square matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.37754576 0.43131543 0.62769984]
 [0.98280604 0.73310827 0.77739381]]


In [16]:
print(randomMatrix[ : ,2])

[0.62769984 0.77739381]


In [18]:
randomMatrix[1,1:3] = 1 # Slicing
print(randomMatrix)

[[0.37754576 0.43131543 0.62769984]
 [0.98280604 1.         1.        ]]


In [22]:
## Set some rows and columns with any values
z = np.zeros((3,3),dtype = np.int64)
print(z)
z[1,:] = 5
z[ :,-1] = 7
print(z)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [23]:
# Datatypes 
print(z.dtype)

int64


In [26]:
#Matematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element Wise Addition
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [29]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [32]:
# Matrix Multiplication / Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [58]:
#Multiplication(Dot Product) of Vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))



30


In [36]:
print(a)

[1 2 3 4]


In [37]:
print(sum(a))

10


In [38]:
print(x)

[[1 2]
 [3 4]]


In [41]:
print(np.sum(x))
print(np.sum(x,axis=1))

10
[3 7]


In [59]:
# Stacking of arrays
print(a)
b = b + 5
print(b)

[1 2 3 4]
[6 7 8 9]


In [60]:
a = np.stack((a,b),axis=0)

In [68]:
# Reshape a Numpy Array
#print(a)
a = a.reshape((-1,4))
print(a)

[[1 2 3 4]
 [6 7 8 9]]


# Some More Numpy Functions - Statistics
- min, max
- mean 
- median
- average
- variance
- standard devidation


In [93]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))



[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [99]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [111]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev= np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


# Numpy Random Module

- rand : Random values in a given shape.
- randn : Return a sample (or samples) from the “standard normal” distribution.
- randint : Return random integers from low (inclusive) to high (exclusive).
- random : Return random floats in the half-open interval [0.0, 1.0) 
- choice : Generates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [113]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [130]:
np.random.seed(1)
np.random.shuffle(a)
print(a)



[7 7 8]


In [126]:
#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)


[[ 0.15425552 -0.13847914  0.08830793]
 [-1.37581904  0.12538437 -0.78782392]]
[7 7 8]
4
